[tools]
python = "3.12.12"
trunk = "1.3.4"

[tasks]
lint = "trunk check --all"
fmt = "trunk fmt"
test = "pytest datachain/tests/basic"
codegen = "echo 'no codegen'"
install = "pip install -e ."
ci = { depends = ["lint", "test"] }
